### ISSUE TITLE
empty response findfacebookid.com

### ISSUE THREAD

**Issue by remster85** [scoliann/TinderFaceScraper#2]
Hi,
I tried to use it but I got no content in my response.
Instead, I have used https://findmyfbid.com and it gave me a clue of why there was a no content response.
I had to (temporarily) enable search engines to find me.

**Comment by scoliann** [comment]
What do you mean by "I got no content in my response"?  And also, how did you enable search engines to find you?  Is that a FaceBook setting?

**Comment by remster85** [comment]
When I hit the button find my facebook id after filling out the field with my facebook page url, nothing happens.
There is a POST REQUEST sent to the website with a HTTP response whose length is 0.
I suggest using the url I mentionned in the first post.
They send a meaningful response and guide you how to enable your profile visibility to search engines : 
https://www.facebook.com/help/392235220834308

**Comment by scoliann** [comment]
Interesting!  This issue seems to have just started in the past few days.  Thank you for sharing.  So you're saying that https://findmyfbid.com and http://findfacebookid.com/ started working after you enabled your profile to be visible to search engines?

**Comment by opensource91** [comment]
https://findmyfbid.in/ works even if visibility setting is set to 'No'

**Comment by opensource91** [comment]
#6

**Comment by scoliann** [comment]
Closing, as https://findmyfbid.in/ seems to be working correctly to fill the function of https://findmyfbid.com and http://findfacebookid.com/, which now appear to have complications.  The README has been updated with the new link.
