### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] error while execution the script

### ISSUE THREAD

**Issue by remster85** [scoliann/TinderFaceScraper#3]
Hi,
I have tried to execute the script with my facebook parameters and  I got the error [SSL: CERTIFICATE_VERIFY_FAILED].
I have tried to verify=false the post and get requests and all I receive is tinder rate limit pictures.
Thanks for helping out.

**Comment by scoliann** [comment]
Hmm, this is the first time I have heard of this issue.  You said "all I receive is tinder rate limit pictures".  Does this mean the script is indeed downloading pictures, just at a rate-limited pace?

**Comment by remster85** [comment]
It's downloading the same pictures many time.
The picture says 
![tinder_rate_limited_id_1493492829643_0_0](https://cloud.githubusercontent.com/assets/23420546/25558882/e4e25584-2cfd-11e7-8793-08b530e53bdd.jpg)

Can you try with adding verify=false to your requests?

**Comment by scoliann** [comment]
If you notice, that photo says "Out of Likes Today".  Tinder gives you a limited number of likes each day (unless you are paying for an account), but an unlimited number of dislikes.  This is why I dislike every recommended person in the script.

**Comment by remster85** [comment]
It's working today indeed!
