### ISSUE TITLE
Unable to find FaceBook token

### ISSUE THREAD

**Issue by opensource91** [scoliann/TinderFaceScraper#5]
Hi scoliann, in the fourth step for getting the fb token, what should I do after clicking OK?

**Comment by opensource91** [comment]
Tried using the token from https://developers.facebook.com/tools/explorer. Got the following error
```
Traceback (most recent call last):
  File "tinderGetPhotos.py", line 91, in <module>
    x_auth_token = tinderAPI_get_xAuthToken(facebook_token, facebook_id)
  File "tinderGetPhotos.py", line 32, in tinderAPI_get_xAuthToken
    x_auth_token = r.json()['token']
KeyError: 'token'
```

**Comment by scoliann** [comment]
Hi opensource91, I just updated the README.md file.  https://developers.facebook.com/tools/explorer is not the proper place to go, as we are looking for a token specific to logging into Tinder.  As explained in the updated README, the Tinder token can be found by opening Developer Tools in Google Chrome and navigating over to the Network tab prior to clicking OK in step 4.  The RESTful requests will show below, and you will be able to click on the POST request https://www.facebook.com/v2.6/dialog/oauth/confirm?dpr=1.

**Comment by opensource91** [comment]
Thanks! It worked
